sudo: required
language: python
python:
- '3.6'
addons:
  sonarcloud:
    organization: AT11
    token:
      secure: "$SONAR_TOKEN"
install:
- pip3 install -r requirements.txt
script:
- behave trello/api/features --tags=~@wip --tags=~@defect
notifications:
  email: true
before_install:
- openssl aes-256-cbc -K $encrypted_5462a14bab70_key -iv $encrypted_5462a14bab70_iv
  -in config.json.enc -out config.json -d
